name: HWX_REGISTRY
label: Schema Registry
description: HortonWorks Schema Registry. <span class="error">Requires Java 8.</span>
version: 0.1.0

compatibility:
  cdhVersion:
    max: '5'
    min: 5.7.0

icon: images/icon.png

inExpressWizard: false

runAs:
  user: hwx-registry
  group: hwx-registry
  principal: hwx-registry

maxInstances: 1

parcel:
  repoUrl: https://github.com/nomr/hwx-registry-parcel/releases/download/v0.4.0+registry0.0.1
  requiredTags: [hwx-registry]

serviceDependencies:

rolesWithExternalLinks:
- HWX_REGISTRY_SERVER

commands:
- name: service_cmd_1
  label: CMD_1
  description: CMD_1
  roleCommand: server_cmd_1
  roleName: HWX_REGISTRY_SERVER
  runMode: single

parameters:
- name: java_home
  configName: java.home
  label: Java 8 Home
  description: Path to Java 8
  required: true
  configurableInWizard: true
  type: path
  pathType: serviceSpecific
  default: /usr/java/default

roles:
- name: HWX_REGISTRY_SERVER
  label: SchemaRegistry Server
  pluralLabel: SchemaRegistry Servers
  jvmBased: 'true'

  externalLink:
    name: webserver_web_ui
    label: CA Server
    url: 'https://${host}:${port}'

  startRunner:
    args: [run]
    environmentVariables:
      BIGTOP_JAVA_MAJOR: 8
      LOG_DIR: '${log_dir}'
      JAVA_HOME: '${java_home}'
    program: scripts/control.sh

  commands:
  - name: server_cmd_1
    label: CMD_1
    description: CMD_1
    expectedExitCodes: [0]
    requiredRoleState: stopped
    commandRunner:
      program: scripts/exec.sh
      args: ['rm','-f', '${tls_keystore_location}']

  topology:
    maxInstances: 1
    minInstances: 1

  logging:
    dir: /var/log/hwx-registry
    filename: server.log
    loggingType: other
    modifiable: false

  parameters:
  - name: port
    configName: port
    label: Server Port
    description: The port for the SchemaRegistry to listen on.
    required: true
    type: port
    min: 1024
    default: 22443

  configWriter:
    auxConfigGenerators:
    - filename: registry.yaml
      sourceFilename: aux/registry.yaml

    generators:
    - filename: server.hadoop_xml
      configFormat: hadoop_xml
      includedParams:
      - port
      additionalConfigs:
      - {key: days, value: '1095'}
      - {key: keySize, value: '2048'}
      - {key: keyPairAlgorithm, value: RSA}
      - {key: signingAlgorithm, value: SHA256WITHRSA}
      - {key: keyStoreType, value: jks}
      - {key: caHostname, value: '${host}'}
      - {key: reorderDn, value: true}

#gateway:
#  alternatives:
#    name: tls-conf
#    priority: 50
#    linkRoot: /etc/hwx-registry
#  scriptRunner:
#    program: scripts/cc.sh
#    args: [deploy]
#  configWriter:
#    auxConfigGenerators:
#    - filename: tls-conf/client.sh
#      sourceFilename: scripts/client.sh
#    generators:
#    - filename: tls-conf/tls-service.hadoop_xml
#      configFormat: hadoop_xml
#      includedParams: [ ]
#      additionalConfigs:
#      - {key: days, value: '1095'}
#      - {key: keySize, value: '2048'}
#      - {key: keyPairAlgorithm, value: RSA}
#      - {key: signingAlgorithm, value: SHA256WITHRSA}
#      - {key: keyStoreType, value: jks}
#      - {key: caHostname, value: '@@CA_HOSTNAME@@'}
#      - {key: port, value: '@@CA_PORT@@'}
#      - {key: reorderDn, value: true}
#    peerConfigGenerators:
#    - roleName: HWX_REGISTRY_SERVER
#      filename: tls-conf/tls-service.properties
#      params: [tls_port]
