name: HWX_REGISTRY
label: Schema Registry
description: HortonWorks Schema Registry. <span class="error">Requires Java 8.</span>
version: 0.1.0

compatibility:
  cdhVersion:
    max: '5'
    min: 5.7.0

icon: images/icon.png

inExpressWizard: false

runAs:
  user: hwx-registry
  group: hwx-registry
  principal: hwx-registry

maxInstances: 1

parcel:
  repoUrl: https://github.com/nomr/hwx-registry-parcel/releases/download/v0.4.0+registry0.0.1
  requiredTags: [hwx-registry]

serviceDependencies:
- name: ZOOKEEPER
  required: true

rolesWithExternalLinks:
- HWX_REGISTRY_SERVER

commands:
- name: service_cmd_1
  label: CMD_1
  description: CMD_1
  roleCommand: server_cmd_1
  roleName: HWX_REGISTRY_SERVER
  runMode: single

parameters:
- name: java_home
  configName: java.home
  label: Java 8 Home
  description: Path to Java 8
  required: true
  configurableInWizard: true
  type: path
  pathType: serviceSpecific
  default: /usr/java/default

roles:
- name: HWX_REGISTRY_SERVER
  label: Server
  pluralLabel: Servers
  jvmBased: 'true'

  externalLink:
    name: webserver_web_ui
    label: Registry
    url: 'https://${host}:${port}'

  startRunner:
    args: [run]
    environmentVariables:
      BIGTOP_JAVA_MAJOR: 8
      LOG_DIR: '${log_dir}'
      JAVA_HOME: '${java_home}'
      REGISTRY_HEAP_OPTS: '-Xmx${jvm_heap_size}m -Xms${jvm_heap_size}m'
      REGISTRY_JVM_PERFORMANCE_OPTS: '${jvm_options}'
      HWX_REGISTRY_PORT: '${port}'
      HWX_REGISTRY_STORAGE_LOCATION: '${registry_home}'
      HWX_REGISTRY_ZK_ROOT: '${zk_root}'
      HWX_REGISTRY_SP: '${storage_provider}'
      HWX_REGISTRY_SP_DB_HOSTNAME: '${storage_provider_db_hostname}'
      HWX_REGISTRY_SP_DB_PORT: '${storage_provider_db_port}'
      HWX_REGISTRY_SP_DB_NAME: '${storage_provider_db_name}'
      HWX_REGISTRY_SP_DB_USER: '${storage_provider_db_user}'
      HWX_REGISTRY_SP_DB_PASSWORD: '${storage_provider_db_password}'
    program: scripts/control.sh

  commands:
  - name: server_cmd_1
    label: CMD_1
    description: CMD_1
    expectedExitCodes: [0]
    requiredRoleState: stopped
    commandRunner:
      program: scripts/exec.sh
      args: ['rm','-f', '${tls_keystore_location}']

  topology:
    maxInstances: 1
    minInstances: 1

  logging:
    dir: /var/log/hwx-registry
    filename: server.log
    loggingType: other
    modifiable: false

  parameters:
  - name: registry_home
    configName: registry_home
    label: Schema Registry home
    description: The home directory for registry
    required: true
    type: path
    pathType: localDataDir
    mode: "0750"
    default: /var/lib/hwx-registry

  - name: port
    configName: port
    label: Server Port
    description: The port for the SchemaRegistry to listen on.
    required: true
    type: port
    min: 1024
    default: 23443

  - name: zk_root
    configName: zk_root
    label: Zookeeper ZNode root
    description: Zookeeper ZNode root
    required: true
    type: path
    pathType: serviceSpecific
    conformRegex: /.*
    default: /hwx-registry

  - name: storage_provider
    label: Storage Provider
    description: The type of storage provider
    required: true
    type: string_enum
    validValues: [InMemory, MySQL, PostgreSQL, Oracle]
    default: InMemory

  - name: storage_provider_db_hostname
    label: Storage Provider DataSource Host
    description: The hostname of the datasource
    required: true
    configurableInWizard: true
    type: uri
    default: localhost

  - name: storage_provider_db_port
    label: Storage Provider Database Port
    description: The database port number. The default (0) uses the driver's default port.
    required: true
    configurableInWizard: true
    type: port
    outbound: true
    zeroAllowed: true
    default: 0

  - name: storage_provider_db_name
    label: Storage Provider Database Name
    description: The name of the database for schema_registry
    required: true
    configurableInWizard: true
    type: string
    default: schema_registry

  - name: storage_provider_db_user
    label: Storage Provider DataSource User
    description: Username used to login to data source
    required: true
    configurableInWizard: true
    type: string
    default: hwx-registry

  - name: storage_provider_db_password
    label: Storage Provider DataSource Password
    description: Password used for connecting to data source
    required: true
    configurableInWizard: true
    sensitive: true
    type: password

  - name: jvm_heap_size
    configName: jvm.heap.size
    label: Java Maximum(and Initial) heap size
    description: Java's heap size set using -Xmx and -Xms
    required: true
    type: memory
    unit: megabytes
    scaleFactor: 1.3
    autoConfigShare: 100
    softMin: 512
    default: 512

  - name: jvm_options
    configName: jvm.options
    label: Java Performance Options
    description: Java performance options.
    required: true
    type: string_array
    separator: ' '
    default:
    - -server
    - -XX:+UseParNewGC
    - -XX:+UseConcMarkSweepGC
    - -XX:+CMSClassUnloadingEnabled
    - -XX:+CMSScavengeBeforeRemark
    - -XX:+DisableExplicitGC
    - -Djava.awt.headless=true

  configWriter:
    auxConfigGenerators:
    - filename: registry.envsubst.yaml
      sourceFilename: aux/registry.envsubst.yaml

    generators:
    - filename: server.hadoop_xml
      configFormat: hadoop_xml
      includedParams:
      - port
      additionalConfigs:
      - {key: days, value: '1095'}
      - {key: keySize, value: '2048'}
      - {key: keyPairAlgorithm, value: RSA}
      - {key: signingAlgorithm, value: SHA256WITHRSA}
      - {key: keyStoreType, value: jks}
      - {key: caHostname, value: '${host}'}
      - {key: reorderDn, value: true}

#gateway:
#  alternatives:
#    name: tls-conf
#    priority: 50
#    linkRoot: /etc/hwx-registry
#  scriptRunner:
#    program: scripts/cc.sh
#    args: [deploy]
#  configWriter:
#    auxConfigGenerators:
#    - filename: tls-conf/client.sh
#      sourceFilename: scripts/client.sh
#    generators:
#    - filename: tls-conf/tls-service.hadoop_xml
#      configFormat: hadoop_xml
#      includedParams: [ ]
#      additionalConfigs:
#      - {key: days, value: '1095'}
#      - {key: keySize, value: '2048'}
#      - {key: keyPairAlgorithm, value: RSA}
#      - {key: signingAlgorithm, value: SHA256WITHRSA}
#      - {key: keyStoreType, value: jks}
#      - {key: caHostname, value: '@@CA_HOSTNAME@@'}
#      - {key: port, value: '@@CA_PORT@@'}
#      - {key: reorderDn, value: true}
#    peerConfigGenerators:
#    - roleName: HWX_REGISTRY_SERVER
#      filename: tls-conf/tls-service.properties
#      params: [tls_port]
