language: java
install: true
script:
  - make
deploy:
  provider: releases
  api-key:
    secure: o6H8aM+CekSzIZ5KIkxSsW+ar6ELpCDWCg94+7gwhPQtaxivkmog2TI5sN+QNW8+Z2+0cHNfiWgOC4caSZQ1uVXTCpwX3+GCxKgvtswUx7qRtuqFEfmrbEgOSBJMCIsj5RlL+Os2vlgdx+KIraBwsbf8CYdR/2J2/L3WsVSSX2J58/6lCsYq27kxcp92+z3RTP6lkDVQujx0enmbFif1yUz2es8BLLK8xz7WO/nd7+Q7KMEVGzsu9qdLajMiAjcsZhiZm0o6vkc7O35d2DlSRSCikVGIGbjIlk6U+e14pfl5gVSD0juz0sBRpCLaTvwqyNKeJd7keFCML8wuiwdSpyQYbvdg1kN5wYrQ4Q+IlI0tdlhmV3lsmO7ZIX8Oou2NGlsIFBPX5FN1Ct7TF8xIsWekzeQLTWWMZdfl6cpQwWgzP8I5VJji2xOZ2B2GZbBBqFCXPQPBmcm1YScdLTqqhuvERhoh8dieHGcSnSLjnnVVc98UsWXzzcnBzMUx9epKWR1s6dUBhDyVc/w77oTdfF4pQO0DpgX7VLFvcWYOiY1nXNMI0LZ1r2ul3zln4LjVSRzcCdi5XQZBkEFCkQduocFSfqZLVPWq6mjrMI9DSdeGRyz9NJ7QpnaThvoGIqcg8rWuU3HkPya41bvQE5nF8dl1x/5fKHVCQrCVH4m7dvE=
  file_glob: true
  file:
    - NIFI-*.jar
  skip_cleanup: true
  on:
    tags: true
